<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="GroupShutterSwitch" Id="{9aebf698-8609-4143-8f8a-6a4a1a3cf539}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK GroupShutterSwitch
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="GroupShutterSwitch">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>