<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SimpleButtonWithHold" Id="{f088760e-ef23-410b-b173-1afa982e1c6d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SimpleButtonWithHold
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SimpleButtonWithHold">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>