<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UpStopDownButton" Id="{c21751f0-94cd-4281-8a12-825434e0a956}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK UpStopDownButton
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="UpStopDownButton">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>