<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_UpdateEventTimestampWithSystemTime" Id="{a78d0f17-51b7-4edd-989c-31a4ad70437c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_UpdateEventTimestampWithSystemTime
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME;
	stFileTime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW => stFileTime.dwLowDateTime,
				timeHiDW => stFileTime.dwHighDateTime);
stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);]]></ST>
    </Implementation>
    <LineIds Name="F_UpdateEventTimestampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>